name: Build & Release Android APK

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build_android:
    name: Build Android APK
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-artifacts
          path: build/app/outputs/apk/release/*.apk

  release:
    name: Create Release
    runs-on: windows-latest
    needs: build_android

    steps:
      - name: Download Android Artifacts
        uses: actions/download-artifact@v3
        with:
          name: android-artifacts
          path: ./android

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: android/*.apk
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
